### ISSUE TITLE
MCM subset generator

### ISSUE THREAD

**Issue by wolfiex** [wolfiex/DSMACC-testing#70]
KPP generates f77 and not f90 files for non main mcm mechanisms. 
@pb866 any ideas?

**Comment by wolfiex** [comment]
Only if partial selection of species based on ICS file is selected.

**Comment by wolfiex** [comment]
IF CO2 exists, do not include again! Add in original file!

**Comment by wolfiex** [comment]
All Fixed - Just need to add R species def to the model

**Comment by pb866** [comment]
Script doesn't work for stoichiometric indices with periods. Script assumes number before the period is a species.

Fix regex matching on species (0.324SPEC <- period matching)

**Comment by wolfiex** [comment]
Specs set purge, eqn's fine.

**Comment by wolfiex** [comment]
fixed #76
