### ISSUE TITLE
Revert changes in Makefile for make update_submodule

### ISSUE THREAD

**Issue by pb866** [wolfiex/DSMACC-testing#71]
make update_submodule should be:
git submodule update --recursive (without --remote that gave a git error message)
git pull did not do anything, if the submodule is up to date. TUV was only downloaded with git submodule update.
This also leaves the possibility for developers to test out the submodules and then release the changes themselves by pulling the changed version and commit changes themselves.

**Comment by wolfiex** [comment]
@pb866 
The earth git version is different to the most current. Remote works fine, just not on 1.7.

It is therefore that the foreach loop and a pull request (effectively a merge for any new/updated files whilst keeping the user changed ones ones). 

> git pull did not do anything, if the submodule is up to date
That is the idea!
