### ISSUE TITLE
KPP can't read data files when run as part of `make kpp`

### ISSUE THREAD

**Issue by kilicomu** [wolfiex/DSMACC-testing#81]
When `make kpp` is run from the DSMACC top-level directory, the final step fails with errors of the following type:

```
Fatal error : FILENAME: Can't read file
```

where FILENAME denotes a data file required.  Attached is `strace` output - kpp seems to look in very particular places for files, and these places are not valid search locations from the top-level DSMACC directory in which kpp is run when compiling.

[kpp_strace.txt](https://github.com/wolfiex/DSMACC-testing/files/1372142/kpp_strace.txt)

**Comment by wolfiex** [comment]
You need to specify the path to KPP_HOME within the .bash_profile / startup script. 

http://wiki.seas.harvard.edu/geos-chem/index.php/FlexChem
